# Generated by Django 4.2.7 on 2023-11-29 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_backend', '0003_asistenciacoordinacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenciaFicha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
