# Generated by Django 4.2.7 on 2023-11-29 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_backend', '0004_asistenciaficha'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenciaFichaHorarioFicha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AsistenciaHorarioPorDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura', models.CharField(max_length=45)),
            ],
        ),
    ]
