# Generated by Django 4.2.7 on 2023-11-29 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_backend', '0005_asistenciafichahorarioficha_asistenciahorariopordia'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenciaInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_institucional', models.CharField(max_length=50)),
            ],
        ),
    ]
