# Generated by Django 4.2.7 on 2023-11-29 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_backend', '0006_asistenciainstructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenciaNovedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
