# Generated by Django 4.2.7 on 2023-11-29 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_backend', '0007_asistencianovedad'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenciaPrograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_programa', models.CharField(max_length=45)),
            ],
        ),
    ]
